# Generated by Django 3.0.6 on 2022-02-23 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachefile',
            name='up_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间'),
        ),
        migrations.AddField(
            model_name='file',
            name='up_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间'),
        ),
    ]
