# Generated by Django 3.0.6 on 2022-03-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachefile',
            name='big_number_name',
            field=models.CharField(max_length=255, verbose_name='大编号名'),
        ),
        migrations.AlterField(
            model_name='cachefile',
            name='game_name',
            field=models.CharField(choices=[(0, 'NSG'), (1, 'AOW')], max_length=255, verbose_name='游戏名'),
        ),
        migrations.AlterField(
            model_name='cachefile',
            name='language',
            field=models.CharField(choices=[(0, 'CN'), (1, 'IN'), (2, 'VN'), (3, 'KR'), (4, 'JP'), (5, 'EN'), (6, 'ZH'), (7, 'TH'), (8, 'MY')], max_length=255, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='cachefile',
            name='localization',
            field=models.CharField(choices=[(0, '原版'), (1, '改版'), (2, '预约'), (3, '立即下载')], max_length=255, verbose_name='本地化'),
        ),
        migrations.AlterField(
            model_name='cachefile',
            name='make_mode',
            field=models.CharField(choices=[(0, 'UE'), (1, 'AE'), (2, '剪辑')], max_length=255, verbose_name='制作模式'),
        ),
        migrations.AlterField(
            model_name='cachefile',
            name='producer',
            field=models.CharField(max_length=255, verbose_name='制作人'),
        ),
        migrations.AlterField(
            model_name='cachefile',
            name='run_state',
            field=models.CharField(max_length=255, verbose_name='数据情况'),
        ),
        migrations.AlterField(
            model_name='cachefile',
            name='size',
            field=models.CharField(choices=[(0, '16:9'), (1, '9:16'), (2, '1:1')], max_length=255, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='file',
            name='big_number_name',
            field=models.CharField(max_length=255, verbose_name='大编号名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='game_name',
            field=models.CharField(choices=[(0, 'NSG'), (1, 'AOW')], max_length=255, verbose_name='游戏名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(choices=[(0, 'CN'), (1, 'IN'), (2, 'VN'), (3, 'KR'), (4, 'JP'), (5, 'EN'), (6, 'ZH'), (7, 'TH'), (8, 'MY')], max_length=255, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='file',
            name='localization',
            field=models.CharField(choices=[(0, '原版'), (1, '改版'), (2, '预约'), (3, '立即下载')], max_length=255, verbose_name='本地化'),
        ),
        migrations.AlterField(
            model_name='file',
            name='make_mode',
            field=models.CharField(choices=[(0, 'UE'), (1, 'AE'), (2, '剪辑')], max_length=255, verbose_name='制作模式'),
        ),
        migrations.AlterField(
            model_name='file',
            name='producer',
            field=models.CharField(max_length=255, verbose_name='制作人'),
        ),
        migrations.AlterField(
            model_name='file',
            name='production_date',
            field=models.DateField(verbose_name='制作日期'),
        ),
        migrations.AlterField(
            model_name='file',
            name='run_state',
            field=models.CharField(max_length=255, verbose_name='数据情况'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(choices=[(0, '16:9'), (1, '9:16'), (2, '1:1')], max_length=255, verbose_name='尺寸'),
        ),
    ]
